# Configuration for Alacritty, the GPU enhanced terminal emulator.
# Thanks: github.com/Alph4rd
# alacritty.toml

[colors.bright]
black = "#d0d0d0"
blue = "#3071db"
cyan = "#A45A6C"
green = "#4db5bd"
magenta = "#c1b4a9"
red = "#da8548"
white = "#dfdfdf"
yellow = "#A45A6C"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#1c1f24"
blue = "#C79D8F"
cyan = "#d2738a"
green = "#A45A6C"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#e0e0e0"
yellow = "#da8548"

[colors.primary]
background = "#000000"
foreground = "#c1b4a9"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.75

[window.dimensions]
columns = 70
lines = 25